### PR TITLE
Various additions to SQL Nexus

### PR DESCRIPTION
**Pull request by PiJoCoder**

### CODE REVIEW

**Comment by PiJoCoder** [comment]
Tempdb space usage by object report

image


image

**Comment by PiJoCoder** [comment]
Active Traces and Xevents

This shows up for both Traces and Xevents now

image


image

**Comment by PiJoCoder** [comment]
Expensive events Best practices rule show the right file now

image

**Comment by PiJoCoder** [comment]
AlwaysOn event is under Microsoft Xevents

image

**Comment by PiJoCoder** [comment]
If you import data Query Store.sql (perf collection) from SQL 2022 server you will see all of these new tables

tbl_query_store_wait_stats
tbl_database_query_store_options
tbl_query_store_query_hints
tbl_query_store_plan_feedback
tbl_query_store_query_variant

**Comment by PiJoCoder** [comment]
@asavioli, if you have a chance to test and review these changes, I'd appreciate your feedback. Thanks

**Review by asavioli — COMMENTED** [review]
Collected log scout with general perf + AlwaysOn scenario and loaded into Nexus

Confirmed the new Tempdb Space Usage report. Not sure if some data at the bottom would be expected

image

Confirmed the column expensive event showing up now for the traces, not only for XE

image

it seems the best practices report is still showing the wrong file name for the expensive events

image


Confirmed AlwaysOn_Health is now showing up under Microsoft XEvents

image

Confirmed the new tables are being created for Query Store on SQL 2022

image

**Review by asavioli — DISMISSED** [review]
Tested after the new push. Now best practices is showing correct file name for the expensive XE events

image

**Review by asavioli — APPROVED** [review]

**Pull request merged**
