### PR TITLE
Repl metadata text rowset

### PR DESCRIPTION
**Pull request by JamesFerebee**
Nexus has been configured to import the tables below from SQLLogScout -

repl_sourceserver
repl_msdb_jobs
repl_msarticles  
repl_mscached_peer_lsns  
repl_msdistribution_agents  
repl_msdistribution_history  
repl_mslogreader_agents  
repl_mslogreader_history  
repl_msmerge_agents  
repl_msmerge_articlehistory  
repl_msmerge_history  
repl_msmerge_identity_range_allocations  
repl_msmerge_sessions  
repl_msmerge_subscriptions  
repl_mspublication_access  
repl_mspublications  
repl_mspublicationthresholds  
repl_mspublisher_databases  
repl_msqreader_agents  
repl_msqreader_history  
repl_msrepl_backup_lsns  
repl_msrepl_commands_oldest  
repl_msrepl_commands_newest  
repl_msrepl_errors  
repl_msrepl_identity_range  
repl_msrepl_originators  
repl_msrepl_transactions_oldest  
repl_msrepl_transactions_newest  
repl_msrepl_version  
repl_msreplication_monitordata  
repl_mssnapshot_agents  
repl_mssnapshot_history  
repl_mssubscriber_info  
repl_mssubscriber_schedule  
repl_mssubscriptions  
repl_mssync_states  
repl_mstracer_history  
repl_mstracer_tokens  
repl_msRedirected_Publishers  
repl_msreplservers  
repl_sysservers  
repl_msrepl_agent_jobs

### CODE REVIEW

**Comment by PiJoCoder** [comment]
Thanks @JamesFerebee this is massive amount of effort. 
Imports work fine in SQL Nexus

**Comment by PiJoCoder** [comment]
Can you double check the source query for this rowset and make sure it produces data?

<Rowset name="tbl_repl_sourceserver" enabled="true" identifier="-- repl_sourceserver --" type="RowsetImportEngine.TextRowset">

**Comment by JamesFerebee** [comment]
> Can you double check the source query for this rowset and make sure it produces data?
> 
> `<Rowset name="tbl_repl_sourceserver" enabled="true" identifier="-- repl_sourceserver --" type="RowsetImportEngine.TextRowset">`

Hi @PiJoCoder. It appears to import properly for me. Please find below. If it isn't for you, can you please make sure you have the latest build of logscout? That was the most recent field edited.

image

image

**Comment by PiJoCoder** [comment]
> > Can you double check the source query for this rowset and make sure it produces data?
> > `<Rowset name="tbl_repl_sourceserver" enabled="true" identifier="-- repl_sourceserver --" type="RowsetImportEngine.TextRowset">`
> 
> Hi @PiJoCoder. It appears to import properly for me. Please find below. If it isn't for you, can you please make sure you have the latest build of logscout? That was the most recent field edited.
> 
> image
> 
> image

Sorry, I was checking out the wrong branch in LogScout - it looks good! Thank you

**Comment by JamesFerebee** [comment]
> 

Not an issue :) Thank you very much for your diligence and making sure the change is as expected.

**Review by PiJoCoder — APPROVED** [review]
Looks great!

**Comment by JamesFerebee** [comment]
Not a problem! Thank you for your diligence 😊

**Pull request merged**
