### PR TITLE
Fix #232 (report appears if all tables are there) #247 (fix working set trimming report) and #243 (add CCC rule) 

### LINKED ISSUE #232: If a report uses multiple tables it should not appear on SQL Perf Main report when not all tables are present
In this case there are multiple tables in the report datasets. So if one of the tables are missing, but the main one is there - dbo.tbl_dm_db_file_space_usage, the report will be shown as clickable in the SQL Perf Main

insert into @tbl_reports (ReportName, ReportDisplayName, ReportDescription, VersionApplied, Category,  ValidationObject, SeqNo, DataCollection,Manditory, CategorySeq) 
values ('Tempdb_Space_Use_C', 'Tempdb Space Usage', 'Breakdown of space usage in tempdb',  1|2|4|8, 'Performance', '**dbo.tbl_dm_db_file_space_usage**', 4000, 'Tempdb and Trans Collector', 1,3000)

And yet when you click the report, you can get a failure because another table is missing

image

### PR DESCRIPTION
**Pull request by hacitandogan**
worked on the issue #232
Although this should prevent those errors , for future maybe we should consider some of our reports to handle these kind of situations.(Especially when the partial information is still meaningfull even if you have some data missing )

### CODE REVIEW

**Comment by PiJoCoder** [comment]
@hacitandogan thank you for all this work. Just saw this today. I'll be testing and providing feedback. Thank you

**Comment by PiJoCoder** [comment]
@hacitandogan thank you

- Tested working set trimming report - looks good
- Tested multiple tables report - tempdb space usage - looks good
- For usp_CCC_Enabled, add an "EXEC usp_CCC_Enabled" at the bottom of PerfStatsAnalysis.sql to activate the rule
- Could you undo the changes to NexusReports/**NexusReports.rptproj.rsuser** it gets automatically modified every time you make a report change and I personally reverse the change to it as this change is not relevant. There may be a way to disable changing the user's property here, but I have investigated. For now, just dicard the change to this file and push 
- Can you do a **git pull upstream master**  since we merged a PR today and the Master is updated and push

**Comment by hacitandogan** [comment]
@PiJoCoder
Thank you.
I did the modifications and tried to revert .rsuser  file to its original  yet it still looks like a commit , could you please review and comment ?

**Comment by PiJoCoder** [comment]
> @PiJoCoder Thank you. I did the modifications and tried to revert .rsuser file to its original yet it still looks like a commit , could you please review and comment ?

Looks like it worked. I don't see the file listed as one of the changed ones:
image

**Comment by PiJoCoder** [comment]
Tested Common criteria compliance rule - looks good
image

**Review by PiJoCoder — APPROVED** [review]
Looks great

**Comment by PiJoCoder** [comment]
Thank you @hacitandogan - great work on these!

**Pull request merged**
