### PR TITLE
Ram nexus

### PR DESCRIPTION
**Pull request by ram2ybabu**
Hi Team, 

Please review the the code change and let me know if any modifications required. 

Thanks
Ram

### CODE REVIEW

**Comment by ram2ybabu** [comment]
> Perhap name this CustomXELImporter or something like that?

modified the class name with the suggested name

**Comment by PiJoCoder** [comment]
hey @ram2ybabu , did you close the PR by accident? I was going to test this and see if we can merge it into Master

**Comment by PiJoCoder** [comment]
@ram2ybabu , just following up on this. I remember you were planning to add some more to this PR. Not sure if I remember this right. Please let me know if we should proceed with merging.

**Comment by ram2ybabu** [comment]
> @ram2ybabu , just following up on this. I remember you were planning to add some more to this PR. Not sure if I remember this right. Please let me know if we should proceed with merging.

I have tested the  PowerBI template, its working as expected. I can create a test build for our team to test and we can proceed with merging master

**Comment by PiJoCoder** [comment]
@ram2ybabu sounds good. Let's try a build and plan to merge in next meeting. Looks like conflicts with Master so we can resolve together if you would like

**Pull request merged**
