### PR TITLE
Multiple SQL Nexus fixes (#250, #251, #238, #254)

### PR DESCRIPTION
**Pull request by PiJoCoder**
1. Allow the ability to minimize Cmd prompt window when Relog.exe imports Performance .BLG files into SQL Nexus

   image

1. Allow the ability to import XEL files using local server time, rather than UTC time (default) via ReadTrace
 
   image

1. Fixed "Save my options" functionality in the import window to ensure the import options were really saved. Some of the options weren't saved before even though the GUI shows the boxes are checked. 
  
   image

    To test this last fix, 
     - select "Save my options" 
     - then enable one of the import options (for example minimize Cmd Window (relog.exe) ) 
     - Do the import. 
     - Then close the Import dialog 
     - Open it back up 
     - Re-import and ensure the option is still working
 
1. REDO_THREAD_PENDING_WORK wait type is now ignorable type, which means it will not show up in the Bottleneck Analysis report as a bar in the bar chart.

### CODE REVIEW

**Comment by asavioliMSFT** [comment]
REDO_THREAD_PENDING_WORK wait type is now ignorable type, which means it will not show up in the Bottleneck Analysis report as a bar in the bar chart.

Currently I have one nexus loaded where a related wait is the highest one

Current nexus version

image

Version from the PR. We no longer see the REDO_THREAD_PENDING_WORK, but we still can see PARALLEL_REDO_WORKER_WAIT_WORK. I'm wondering if this one could also be ignored



image

**Comment by PiJoCoder** [comment]
Yes, there are many such wait types. Can you file an issue on Github and add this and this other one I sent to Haci the other day

 QDS_ASYNC_QUEUE be an ignorable wait type?

If you can think of others add them to the list.
Thanks

________________________________

**Comment by asavioliMSFT** [comment]
Performed the tests below

- select "Save my options"

- then enable one of the import options (for example minimize Cmd Window (relog.exe) )

- Do the import.

- Then close the Import dialog

- Open it back up

- Re-import and ensure the option is still working



Initially I tested enabling the option minimize cmd during the relog. 
Imported logs twice, after closing the import window. It worked fine
Then I reverted it, that is, unchecked the option to minimize the cmd during relog, since I prefer to see the window. It also worked fine twice.

**Review by asavioliMSFT — APPROVED** [review]

**Review by hacitandogan — DISMISSED** [review]
Tested these changes and all looks fine.
Log capture time ;
image

Readtrace log capture time without local time adjustment;

image


With Local Server Time Option;

image

**Comment by asavioliMSFT** [comment]
> QDS_ASYNC_QUEUE

I think we can. Paul Randal agrees

https://www.sqlskills.com/help/waits/qds_async_queue/

**Review by asavioliMSFT — APPROVED** [review]

**Pull request merged**
