### PR TITLE
Update TextRowsets.xml

### PR DESCRIPTION
**Pull request by asavioli**
adding 2 new columns to be imported on nexus. This is required to support the changes coming from Issue 121 from DiagManager   https://github.com/microsoft/DiagManager/pull/142

### CODE REVIEW

**Comment by PiJoCoder** [comment]
We tested this but SQL Nexus failed to import any of the scripts. Need to find out what is causing this with your change. Perhaps has to do with Report viewer control not being installed in your solution....

**Comment by PiJoCoder** [comment]
@asavioli looking great. It appears that there is one more column that we need to add to the XML rowset 

**persisted_sample_percent**

It is the last column in the table output and seems like a decimal (5,1) will work - as this is a percent.
SQL Nexus finds it and imports it, but because there is no defined data type it uses varchar(24) instead.
Thanks

**Comment by PiJoCoder** [comment]
Also, one more thing that we need to fix in other places too, but can you add this the very first row in the XML rowset. 
    ` <Column name="rownum" type="RowsetImportEngine.BigIntColumn" length="24" valuetoken="ROWNUMBER" />`

Like this

```
 <Rowset name="tbl_dm_db_stats_properties" enabled="true" identifier="-- sys.dm_db_stats_properties --" type="RowsetImportEngine.TextRowset">
     <Column name="rownum" type="RowsetImportEngine.BigIntColumn" length="24" valuetoken="ROWNUMBER" />
     <Column name="database_id" type="RowsetImportEngine.IntColumn" />
      <Column name="database_name" type="RowsetImportEngine.NVarCharColumn" />
      <Column name="schema_name" type="RowsetImportEngine.NVarCharColumn" />
      <Column name="object_name" type="RowsetImportEngine.NVarCharColumn" />

```
This will automatically add a rownum column to the table and will allow us to distinguish imports from startup vs. shutdown script. We end up with duplicated values for each entry because we have Snapshot collected both at startup and shutdown. But for now this will help some with identifying those rows. You will see this thing happeing in the table

image




<Column name="rownum" type="RowsetImportEngine.BigIntColumn" length="24" valuetoken="ROWNUMBER" />

**Comment by asavioli** [comment]
Hello Joseph. Regarding the column persisted_sample_percent: it was introduced only on SQL 2016 SP1 CU4

https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-stats-properties-transact-sql

Because of that, I believe we will need to check the version on the diagmanager script to check whether it be returned or not, won't we?

**Comment by PiJoCoder** [comment]
> Hello Joseph. Regarding the column persisted_sample_percent: it was introduced only on SQL 2016 SP1 CU4
> 
> https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-stats-properties-transact-sql
> 
> Because of that, I believe we will need to check the version on the diagmanager script to check whether it be returned or not, won't we?

Good catch. We have 3 options: 
1. check the version - too complicated
1. leave it as is - and let SQL Nexus import it as a varchar(24)
1. remove it from PSSDIAG

I am leaning towards 2. leave it as is. So no change for you to make then

**Comment by asavioli** [comment]
But I believe that we will have to check the version at least on the diagmanager. If we run that script on a SQL 2014, for example, it will fail with error "column doesn't exist. > > Hello Joseph. Regarding the column persisted_sample_percent: it was introduced only on SQL 2016 SP1 CU4
> 
> > 
> 
> > https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-stats-properties-transact-sql
> 
> > 
> 
> > Because of that, I believe we will need to check the version on the diagmanager script to check whether it be returned or not, won't we?
> 
> 
> 
> Good catch. We have 3 options: 
> 
> 1. check the version - too complicated
> 
> 1. leave it as is - and let SQL Nexus import it as a varchar(24)
> 
> 1. remove it from PSSDIAG
> 
> 
> 
> I am leaning towards 2. leave it as is. So no change for you to make then

**Comment by PiJoCoder** [comment]
> But I believe that we will have to check the version at least on the diagmanager. If we run that script on a SQL 2014, for example, it will fail with error "column doesn't exist. 

Well, you have a point. I got confused that we have to check something on SQL Nexus end. We actually have to do it on the PSSDIAG end. Can you make that change? Here are some samples that work on all versions 

SELECT LEFT(CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)), (CHARINDEX(N'.', CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)))-1)) sql_major_version, CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(20)), 2) AS INT) as sql_major_build

**Comment by asavioli** [comment]
> > But I believe that we will have to check the version at least on the diagmanager. If we run that script on a SQL 2014, for example, it will fail with error "column doesn't exist. 
> 
> 
> 
> Well, you have a point. I got confused that we have to check something on SQL Nexus end. We actually have to do it on the PSSDIAG end. Can you make that change? Here are some samples that work on all versions 
> 
> 
> 
> SELECT LEFT(CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)), (CHARINDEX(N'.', CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)))-1)) sql_major_version, CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(20)), 2) AS INT) as sql_major_build
> 
> 
Sure. Will do that!

**Comment by asavioli** [comment]
> SELECT LEFT(CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)), (CHARINDEX(N'.', CAST(SERVERPROPERTY(N'ProductVersion') AS NVARCHAR(128)))-1)) sql_major_version, CAST(PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS varchar(20)), 2) AS INT) as sql_major_build

script changed to handle the column on the different versions

**Comment by asavioli** [comment]
> <Column name="rownum" type="RowsetImportEngine.BigIntColumn" length="24" valuetoken="ROWNUMBER" />

this change is done on the diagmanager and published. Also added the rownum column on Nexus as you requested.

Have to check next week those points regarding the gitignore or reinstalling teh ReportViewer control

**Pull request merged**
