### PR TITLE
Repl topology

### PR DESCRIPTION
**Pull request by cafealternativo**
Adding Replication Topology report see: [NexusReports/Replication_Topology_C.rdl]

### CODE REVIEW

**Review by PiJoCoder — APPROVED** [review]
Code changes look good. Tested successfully. Thank you for contribution.

**Review by PiJoCoder — CHANGES_REQUESTED** [review]
Further testing shows that we may have to re-write the underlying query. So for now we'll investigate what that would take and if report changes are needed. Based on this we'll go foward

**Review by PiJoCoder — DISMISSED** [review]
Changes look good - tested successfully

**Review by JamesFerebee — APPROVED** [review]
Looks good. Thanks Joseph & Fernando.

**Pull request merged**
